### ISSUE TITLE
App crashing starting first Activity

### ISSUE THREAD

**Issue by cesards** [aravindsagar/ScreenShift#5]
App is always crashing on my Galaxy S6. I would give some feedback from the emulator or device if debug was activated on the app.

Is there anything else I can do in my report?

Thanks, and very useful by the way!!

**Comment by aravindsagar** [comment]
Can you try the latest version of the app? If it's stil crashing, a logcat would be very helpful.

**Comment by cesards** [comment]
It doesn't crash anymore :-)
